[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'touch database/database.sqlite',
    'php artisan config:cache'
]

[start]
cmd = 'php -S 0.0.0.0:$PORT -t public'